title: cyyy's take notes
author: cyyy
email: cyyy824@hotmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  工作,智慧城市,随记,思考.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: cyyy's take notes
  tagline: Developer. Designer
  date_format: "%Y %m %d"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github:  cyyy824
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

#  - jekyll-feed
